name: Release and Update Homebrew

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ecs-voyager
            asset_name: ecs-voyager-${{ github.ref_name }}-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ecs-voyager
            asset_name: ecs-voyager-${{ github.ref_name }}-aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (reduce size)
        run: |
          strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Create archive
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          shasum -a 256 ${{ matrix.asset_name }}.tar.gz > ${{ matrix.asset_name }}.tar.gz.sha256

      - name: Upload release archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.tar.gz
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew-formula:
    name: Update Homebrew Formula
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release artifacts
        run: |
          VERSION="${{ github.ref_name }}"

          # Download both macOS archives
          curl -sL "https://github.com/benbpyle/ecs-voyager/releases/download/${VERSION}/ecs-voyager-${VERSION}-x86_64-apple-darwin.tar.gz" -o x86_64.tar.gz
          curl -sL "https://github.com/benbpyle/ecs-voyager/releases/download/${VERSION}/ecs-voyager-${VERSION}-aarch64-apple-darwin.tar.gz" -o aarch64.tar.gz

          # Calculate SHA256 checksums
          X86_64_SHA256=$(shasum -a 256 x86_64.tar.gz | awk '{print $1}')
          AARCH64_SHA256=$(shasum -a 256 aarch64.tar.gz | awk '{print $1}')

          echo "X86_64_SHA256=${X86_64_SHA256}" >> $GITHUB_ENV
          echo "AARCH64_SHA256=${AARCH64_SHA256}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Update formula
        run: |
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION#v}\"/" Formula/ecs-voyager.rb

          # Update URLs with new version
          sed -i "s|download/v[0-9]\+\.[0-9]\+\.[0-9]\+/|download/${VERSION}/|g" Formula/ecs-voyager.rb

          # Update ARM64 SHA256 (find the sha256 line after aarch64-apple-darwin)
          sed -i "/aarch64-apple-darwin.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${AARCH64_SHA256}\"/" Formula/ecs-voyager.rb

          # Update x86_64 SHA256 (find the sha256 line after x86_64-apple-darwin)
          sed -i "/x86_64-apple-darwin.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${X86_64_SHA256}\"/" Formula/ecs-voyager.rb

      - name: Create PR with updated formula
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are changes
          if git diff --quiet Formula/ecs-voyager.rb; then
            echo "No changes to formula, skipping"
            exit 0
          fi

          # Create a branch for the formula update
          BRANCH_NAME="chore/update-formula-${VERSION}"
          git checkout -b "${BRANCH_NAME}"

          # Commit changes
          git add Formula/ecs-voyager.rb
          git commit -m "chore: update Homebrew formula to ${VERSION}" \
                     -m "Auto-updated by release workflow:" \
                     -m "- Version: ${VERSION#v}" \
                     -m "- ARM64 SHA256: ${AARCH64_SHA256}" \
                     -m "- x86_64 SHA256: ${X86_64_SHA256}"

          # Push branch
          git push origin "${BRANCH_NAME}"

          # Create PR
          gh pr create \
            --title "chore: update Homebrew formula to ${VERSION}" \
            --body "Auto-generated PR to update Homebrew formula" \
            --base master \
            --head "${BRANCH_NAME}"